# Generated by Django 2.1.1 on 2018-09-06 02:55

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='studyhour',
            name='color',
            field=colorfield.fields.ColorField(default='#42d1f4', max_length=18),
        ),
        migrations.AlterField(
            model_name='studyhour',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Course'),
        ),
        migrations.AlterField(
            model_name='studyhour',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studyhour',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
