# Generated by Django 2.1.1 on 2018-09-06 22:47

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20180906_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyhour',
            name='color',
        ),
        migrations.AddField(
            model_name='course',
            name='color',
            field=colorfield.fields.ColorField(default='#42d1f4', max_length=18),
        ),
        migrations.AlterField(
            model_name='studyhour',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studyhour',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
